{% set name = "pyuvdata" %}
{% set version = "1.3.6" %}
{% set sha256 = "5492850440108883fa7a8e83172dac2b8378cb0963e862ee62f80627ef3754e5" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - six >=1.10
    - astropy >=2.0
    - numpy >=1.14.*  # pyuvdata requires this
    - pip
    - python
    - scipy
    - setuptools
  run:
    - six >=1.10
    - astropy >=2.0
    - {{ pin_compatible('numpy') }}
    - python
    - scipy

test:
  requires:
    - healpy
    - nose
    - python-casacore
    - h5py
  imports:
    - pyuvdata
  commands:
    - nosetests pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'an interface for astronomical interferometeric datasets in python'

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
