{% set name = "pyuvdata" %}
{% set version = "2.1.5" %}
{% set sha256 = "4610cfb9cce2b3bccfca19e5670eef327989d21b07dfedb480c3ba95a4887bc1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=35]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - astropy >=3.2.3
    - cython >=0.23
    - numpy >=1.18.*  # pyuvdata requires this
    - h5py
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm
    - pytest-runner
  run:
    - astropy >=3.2.3
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - h5py
    - setuptools_scm

test:
  requires:
    - git
    - astropy-healpix
    - cython >=0.23
    - pytest >=6.2
    - pytest-cases >=3
    - pytest-xdist
    - python-casacore  # [not win]
    - pyyaml
    - setuptools_scm
  imports:
    - pyuvdata
  commands:
    - pytest -vv -s --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
