{% set name = "pyuvdata" %}
{% set version = "2.4.2" %}
{% set sha256 = "cec2a6630f3d3b39511548f94a557ec302057edd4096d5f99434e3d694291f2f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=37]]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - astropy >=5.0.4
    - cython >=0.23
    - docstring_parser >=0.15
    - h5py >=3.1
    - numpy  # pyuvdata needs >=1.20
    - pip
    - pyerfa >=2.0
    - python
    - scipy >=1.5
    - setuptools
    - setuptools_scm <7.0|>=7.0.3
  run:
    - astropy >=5.0.4
    - docstring_parser >=0.15
    - h5py >=3.1
    - {{ pin_compatible('numpy') }}
    - pyerfa >=2.0
    - python
    - scipy >=1.5
    - setuptools_scm <7.0|>=7.0.3

test:
  requires:  # novas and novas_de405 are not included because they aren't on conda
    - git
    - astropy-healpix >=0.6
    - astroquery >=0.4.4
    - cython >=0.23
    - pytest <8
    - pytest-cases >=3.6.9
    - pytest-xdist
    - python-casacore >=3.3  # [not win and py<311]
    - pyyaml >=5.1
    - setuptools_scm <7.0|>=7.0.3
  imports:
    - pyuvdata
  commands:
    - pytest -vv -s --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - plaplant
    - bhazelton
    - pkgw
