{% set name = "pyuvdata" %}
{% set version = "2.1.1" %}
{% set sha256 = "94ce08ac9fa4bcf3f57d8da90e3edf0b91bebbca2243c1b3f8ebd918eec2278c" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 1
  script:
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py<=35]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - astropy >=3.2.3
    - cython
    - numpy >=1.18.*  # pyuvdata requires this
    - h5py
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm
    - pytest-runner
  run:
    - astropy >=3.2.3
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - h5py
    - setuptools_scm

test:
  requires:
    - git
    - astropy-healpix
    - pytest
    - pyyaml
    - setuptools_scm
  imports:
    - pyuvdata
  commands:
    - pytest --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python
  doc_url: https://pyuvdata.readthedocs.io
  dev_url: https://github.com/RadioAstronomySoftwareGroup/pyuvdata

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
