{% set name = "pyuvdata" %}
{% set version = "2.0.2" %}
{% set sha256 = "084a1dc3c383f7663a2be169c70a7587a071310f5594d95f988b501eb82159e8" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script:
    # Add a setup.py bdist_wheel call for setuptools_scm per https://github.com/pypa/setuptools_scm/issues/280
    - {{ PYTHON }} setup.py bdist_wheel --dist-dir=dist
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [win or py<=35]]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - astropy >=3.2.3
    - cython
    - numpy >=1.15.*  # pyuvdata requires this
    - h5py
    - pip
    - python
    - scipy
    - setuptools
    - setuptools_scm
    - pytest-runner
  run:
    - astropy >=3.2.3
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - h5py

test:
  requires:
    - git
    - astropy-healpix
    - pytest
    - python-casacore
    - pyyaml
  imports:
    - pyuvdata
  commands:
    - pytest --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: an interface for astronomical interferometeric datasets in python

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
