{% set name = "pyuvdata" %}
{% set version = "1.5.0" %}
{% set sha256 = "12e7734799e55b05712ad8d3aa38f5cc75b4a17feb417133bd3fd0f252996df5" %}

package:
  name: {{ name }}
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - warnings.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - six >=1.10
    - astropy >=2.0
    - numpy >=1.15.*  # pyuvdata requires this
    - h5py
    - pip
    - python
    - scipy
    - setuptools
    - pytest-runner
  run:
    - six >=1.10
    - astropy >=2.0
    - {{ pin_compatible('numpy') }}
    - python
    - scipy
    - h5py

test:
  requires:
    - git
    - astropy-healpix
    - pytest
    - python-casacore
    - pyyaml
  imports:
    - pyuvdata
  commands:
    - pytest --pyargs pyuvdata

about:
  home: https://github.com/RadioAstronomySoftwareGroup/pyuvdata
  license: BSD 2-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'an interface for astronomical interferometeric datasets in python'

extra:
  recipe-maintainers:
    - bhazelton
    - pkgw
